### ISSUE TITLE
OS X Installation Error

### ISSUE THREAD

**Issue by rawls238** [plloydsmith/rmdcev#3]
I'm receiving this error when I try to install on OS X Catalina: 

```
RcppExports.cpp:341:5: error: no matching function for call to 'R_useDynamicSymbols'
    R_useDynamicSymbols(dll, FALSE);
    ^~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/r/4.0.2_1/lib/R/include/R_ext/Rdynload.h:84:10: note: candidate function not viable: no known conversion from 'int' to 'Rboolean' for 2nd argument
Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value);
```

Installation seems to work on my Ubuntu box, so this is an OS X specific issue.

**Comment by plloydsmith** [comment]
Thanks for leaving a comment. I can recreate this error on a virtual OS X machine but cannot find an easy way to fix it. I'll keep looking into this. This appears to be related to RcppEigen and this issue here

https://github.com/stephenslab/ldshrink/issues/21

and here

https://github.com/RcppCore/Rcpp/issues/846

In the meantime, I suggest using linux or windows and I have added a mac os installation warning in the Readme file.

**Comment by plloydsmith** [comment]
Ok, the mac OS installation issues should be solved now. Let me know if you still have any issues with and if not I will close this comment in 7 days.
